const std = @import("std");
const Builder = std.build.Builder;

pub fn build(b: *Builder) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const libgitz = b.addStaticLibrary(.{
        .name = "gitz",
        .target = target,
        .optimize = optimize,
    });
    libgitz.linkLibC();
    libgitz.addIncludePath("./src/util");
    libgitz.addIncludePath("./src/include");
    libgitz.addIncludePath("./src/include/git2");
    libgitz.addIncludePath("./src/libgit2");
    libgitz.addIncludePath("./include");
    libgitz.addCSourceFiles(&.{
        "src/libgit2/annotated_commit.c",
        "src/libgit2/apply.c",
        "src/libgit2/attr.c",
        "src/libgit2/attrcache.c",
        "src/libgit2/attr_file.c",
        "src/libgit2/blame.c",
        "src/libgit2/blame_git.c",
        "src/libgit2/blob.c",
        "src/libgit2/branch.c",
        "src/libgit2/buf.c",
        "src/libgit2/cache.c",
        "src/libgit2/checkout.c",
        "src/libgit2/cherrypick.c",
        "src/libgit2/clone.c",
        "src/libgit2/commit.c",
        "src/libgit2/commit_graph.c",
        "src/libgit2/commit_list.c",
        "src/libgit2/config.c",
        "src/libgit2/config_cache.c",
        "src/libgit2/config_entries.c",
        "src/libgit2/config_file.c",
        "src/libgit2/config_mem.c",
        "src/libgit2/config_parse.c",
        "src/libgit2/config_snapshot.c",
        "src/libgit2/crlf.c",
        "src/libgit2/delta.c",
        "src/libgit2/describe.c",
        "src/libgit2/diff.c",
        "src/libgit2/diff_driver.c",
        "src/libgit2/diff_file.c",
        "src/libgit2/diff_generate.c",
        "src/libgit2/diff_parse.c",
        "src/libgit2/diff_print.c",
        "src/libgit2/diff_stats.c",
        "src/libgit2/diff_tform.c",
        "src/libgit2/diff_xdiff.c",
        "src/libgit2/email.c",
        "src/libgit2/errors.c",
        "src/libgit2/fetch.c",
        "src/libgit2/fetchhead.c",
        "src/libgit2/filter.c",
        "src/libgit2/graph.c",
        "src/libgit2/hashsig.c",
        "src/libgit2/ident.c",
        "src/libgit2/idxmap.c",
        "src/libgit2/ignore.c",
        "src/libgit2/index.c",
        "src/libgit2/indexer.c",
        "src/libgit2/iterator.c",
        "src/libgit2/libgit2.c",
        "src/libgit2/mailmap.c",
        "src/libgit2/merge.c",
        "src/libgit2/merge_driver.c",
        "src/libgit2/merge_file.c",
        "src/libgit2/message.c",
        "src/libgit2/midx.c",
        "src/libgit2/mwindow.c",
        "src/libgit2/netops.c",
        "src/libgit2/notes.c",
        "src/libgit2/object_api.c",
        "src/libgit2/object.c",
        "src/libgit2/odb.c",
        "src/libgit2/odb_loose.c",
        "src/libgit2/odb_mempack.c",
        "src/libgit2/odb_pack.c",
        "src/libgit2/offmap.c",
        "src/libgit2/oidarray.c",
        "src/libgit2/oid.c",
        "src/libgit2/oidmap.c",
        "src/libgit2/pack.c",
        "src/libgit2/pack-objects.c",
        "src/libgit2/parse.c",
        "src/libgit2/patch.c",
        "src/libgit2/patch_generate.c",
        "src/libgit2/patch_parse.c",
        "src/libgit2/path.c",
        "src/libgit2/pathspec.c",
        "src/libgit2/proxy.c",
        "src/libgit2/push.c",
        "src/libgit2/reader.c",
        "src/libgit2/rebase.c",
        "src/libgit2/refdb.c",
        "src/libgit2/refdb_fs.c",
        "src/libgit2/reflog.c",
        "src/libgit2/refs.c",
        "src/libgit2/refspec.c",
        "src/libgit2/remote.c",
        "src/libgit2/repository.c",
        "src/libgit2/reset.c",
        "src/libgit2/revert.c",
        "src/libgit2/revparse.c",
        "src/libgit2/revwalk.c",
        "src/libgit2/signature.c",
        "src/libgit2/stash.c",
        "src/libgit2/status.c",
        "src/libgit2/strarray.c",
        "src/libgit2/submodule.c",
        "src/libgit2/sysdir.c",
        "src/libgit2/tag.c",
        "src/libgit2/threadstate.c",
        "src/libgit2/trace.c",
        "src/libgit2/trailer.c",
        "src/libgit2/transaction.c",
        "src/libgit2/transport.c",
        "src/libgit2/tree.c",
        "src/libgit2/tree-cache.c",
        "src/libgit2/worktree.c",
    }, &.{
        "-Wall",
        "-W",
        "-Wstrict-prototypes",
        "-Wwrite-strings",
        "-Wno-missing-field-initializers",
    });
    libgitz.install();
    libgitz.installHeadersDirectory("include", "gitz");
}
